# Generated by Django 4.2 on 2023-04-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ima', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('familia', models.CharField(max_length=50, verbose_name='Имя')),
                ('pochta', models.CharField(max_length=100, verbose_name='Почта')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
            ],
        ),
    ]
